### ISSUE TITLE
Release 2.8

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/ocsigenserver#114]
Let's get it out in the next few days!

Major changes:

- New Postgres Ocsipersist backend, OR switch to the [standalone Ocsipersist](https://github.com/ocsigen/ocsipersist) (with Postgres added)
- Compatibility with TyXML `4.0.x`.

We may also want to merge #87. Anything else?

**Comment by vasilisp** [comment]
I can take care of the Ocsipersist switch, it needs to happen (finally).

**Comment by vasilisp** [comment]
We may also want to convert to PPX and eliminate the Camlp4 dependency. We are only using the Lwt Camlp4 syntax, I hope?

**Comment by dannywillems** [comment]
@vasilisp Seems there are some Lwt Camlp4 syntax in
- `src/baselib/ocsigen_message.ml`
- `src/extensions/ocsipersist-psql/ocsipersist.ml`
- `src/baselib/ocsigen_lib_base.ml`

**Comment by vasilisp** [comment]
@dannywillems, I know, PR coming :).

**Comment by vasilisp** [comment]
See https://github.com/ocsigen/ocsigenserver/pull/115.

**Comment by dannywillems** [comment]
@vasilisp Compatibility with 4.04 must be also verified.

**Comment by dannywillems** [comment]
It seems there is a problem with the OPAM ssl package. But I think, as it's not caused by ocsigenserver, it must be OK.

**Comment by vasilisp** [comment]
@dannywillems, I have gotten everything (up to `ocsigen-start`) compiling with an opam-friendly `ssl` branch: https://github.com/vasilisp/ocaml-ssl/tree/pin-friendly . Haven't tested much.

**Comment by dannywillems** [comment]
@vasilisp I think it could be interesting to do a PR.

**Comment by vasilisp** [comment]
@dannywillems, it is not done well, I just put the auto-generated files in the repo as a temporary workaround. They are not supposed to be there. This is the standard autotools annoyance...

**Comment by vasilisp** [comment]
I think the Ocsipersist split gets postponed, see ocsigen/ocsipersist#4.

**Comment by vasilisp** [comment]
Tagged. `opam-repository` PR: https://github.com/ocaml/opam-repository/pull/7914
