### ISSUE TITLE
Memory leak (?)

### ISSUE THREAD

**Issue by jpdeplaix** [ocsigen/ocsigenserver#12]
We noticed on cumulus a uncommon amount of memory took by ocsigenserver.
On startup, it takes 18Mo of RAM and after a few days it takes almost 400Mo.

I tried to reproduce it more quickly and I succeed with a simple DOS, the memory increase of 2Mo per seconds if we keep pushing the reload button of a web navigator.

Note: Reproduced with the latest ocsigenserver, eliom and lwt (all master)

**Comment by balat** [comment]
Probably fixed by https://github.com/ocsigen/eliom/commit/b18c2a4a6be2359045c30f1b5fb7b7b18ab7f64b
