### ISSUE TITLE
use 100% CPU triggering UNIX error EAGAIN "Accept failed"

### ISSUE THREAD

**Issue by sebferre** [ocsigen/ocsigenserver#147]
running: ocsigenserver -V -c myconf.conf
version: 2.9
It uses 100% CPU, and in veryverbose mode, it shows repeatedly
```
ocsigenserver: ocsigen:main: received 0 accepts
ocsigenserver: ocsigen:main: Accept failed: Unix.Unix_error(Unix.EAGAIN, "accept", "")
```

My web application is very basic with a simple form.
[source code](https://bitbucket.org/sebferre/squall2sparql) for Eliom 4 (I am in the process of upgrading it to Eliom6).

Here is the configuration file:
```
<ocsigen>
  <server>
    <port>3838</port>

    <!-- Update all the directories according to your installation -->
    <!-- A default configuration file is usually provided in /etc/ocsigen/ -->
    <logdir>/tmp</logdir>
    <datadir>/tmp</datadir>
    <user>ferre</user>
    <group>users</group>
    <commandpipe>/tmp/ocsigen_command</commandpipe>

    <extension findlib-package="ocsigenserver.ext.staticmod"/>
    <extension findlib-package="ocsigenserver.ext.ocsipersist-dbm"/>
    <extension findlib-package="eliom.server"/>

    <host hostfilter="*">
      <site path="squall">
            <eliom module="./webform.cma" />
      	    <static dir="/home/ferre/prog/ocaml/squall2sparql" />
      </site>
    </host>

  </server>

</ocsigen>
```

**Comment by vouillon** [comment]
I don't understand how this can happen. Lwt should have catched the exception `Unix.Unix_error(Unix.EAGAIN, "accept", "")`

**Comment by vouillon** [comment]
Actually, this might happen if your program is linked against the unix library twice.

**Comment by sebferre** [comment]
Is there a way I can check the "linked twice" ?
I had a hard time succeeding to install a set of compatible opam packages,
and to upgrade my code to Elion 6.3.0 but in the end, I made nothing special.
I switched my opam to a fresh configuration for ocaml 4.05.
eliom.6.3.0, ocsigenserver.2.9, lwt.3.3.0, ocamlnet.4.1.6, ...

**Comment by vouillon** [comment]
You can try to remove `unix.$(CMA)` from this line in the `makefile`:
```
COMMON_OBJ = str.$(CMA) nums.$(CMA) unix.$(CMA) common.$(CMO) lSet.$(CMO)
```
By the way, you should include a directive in `webform.conf` rather than linking your library directly with external libraries:
```
<extension findlib-package="str"/>
```

**Comment by sebferre** [comment]
Great! just by removing the external libraries from COMMON_OBJ, the problem is solved.
Thanks for the help. Maybe it would be worth to give a warning when a library is loaded
twice ?

**Comment by vouillon** [comment]
Well, I'm not sure we have any way of knowing that...
