### ISSUE TITLE
ocsigenserver does not install with OPAM and OCaml 4.07.0

### ISSUE THREAD

**Issue by psteckler** [ocsigen/ocsigenserver#150]
Running "opam install ocsigenserver" with OPAM using OCaml 4.07.0:

```
# File "ocsigen_server.ml", line 1326, characters 8-27:
# Warning 3: deprecated: module Lwt_chan
#  Use module Lwt_io.
# File "_none_", line 1: 
# Error: Files ../baselib/baselib.cma(Ocsigen_commandline)
#        and ../baselib/parsecommandline.cma(Ocsigen_getcommandline)
#        make inconsistent assumptions over interface Ocsigen_getcommandline
```

I see this same error with OPAM installations on two different machines.

**Comment by psteckler** [comment]
Here's a hackish workaround. 

I setup OPAM to keep build directories. In `.opam/4.07.0/build/ocsigenserver.2.9/src`, there are 3 files named `ocisigen_getcommandline.cmi` generated, in the directories `baselib/`, `baselib/commandline/`, and `baselib/nocommandline/`.

I copied the one from `baselib/commandline/` to `baselib/, ran `make`, then `make install`.

That is just a workaround, and a fix to the build system is still needed. I'm not sure whether the workaround produces a correct result, just that it builds.

**Comment by vasilisp** [comment]
Thanks for the report! It should be solved by https://github.com/ocsigen/ocsigenserver/pull/152 (just as hackish).

**Comment by balat** [comment]
Should be solved now. Reopen if you still have a problem.
