### ISSUE TITLE
Ocsigen Server does not compile with current dev version of tyxml.

### ISSUE THREAD

**Issue by balat** [ocsigen/ocsigenserver#151]
Ocsigen Server does not compile with current dev version of Tyxml.

```
# ocamlfind: Package `tyxml.parser' not found
```

@Drup, @vasilisp do you have a plan for this?

**Comment by vasilisp** [comment]
The plan is to transition to `xml-light` or another library. See https://github.com/ocsigen/tyxml/issues/170.

**Comment by balat** [comment]
Fixed
