### ISSUE TITLE
Default config does not work

### ISSUE THREAD

**Issue by kit-ty-kate** [ocsigen/ocsigenserver#181]
I tried to test if ocsigenserver worked by installing `ocsigenserver.2.15.0` and calling `ocsigenserver` with the default config gives me:
```
$ ocsigenserver
Fatal error: exception Ocsigen_extensions.Error_in_config_file("End of tag expected : 'server', line 45, characters 4-15")
```
If I remove the highlighted (commented?) part (+ minor modifications) then it works. Here what was in that part for me (again, untouched):
```
<!--
<findlib path="/home/kit_ty_kate/.opam/4.10/lib"/>
<extension findlib-package="ocsigenserver.ext.ocsipersist-pgsql">
  <!-- the database-tag and its attributes are all optional -->
  <database
    host="localhost"
    port="3000"
    user="kit_ty_kate"
    password="pw"
    database="db"
    unix_domain_socket_dir="./udsd"
  />
</extension>
-->
```

**Comment by jrochel** [comment]
Thanks! This is fixed in commit 0488d6e202f18b921d4ed6785b9fe8a874597ed0 and will soon be published (probably by you, thanks in advance ;) on OPAM : https://github.com/ocaml/opam-repository/pull/17403
