### ISSUE TITLE
opam installation error

### ISSUE THREAD

**Issue by Escapingbug** [ocsigen/ocsigenserver#183]
```
><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocsigenserver failed at
        "/home/anciety/.opam/opam-init/hooks/sandbox.sh build make".

#=== ERROR while compiling ocsigenserver.2.16.0 ===============================#
# context     2.0.6 | linux/x86_64 | ocaml-system.4.09.0 | https://opam.ocaml.org#dda6dba4
# path        ~/.opam/default/.opam-switch/build/ocsigenserver.2.16.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/ocsigenserver-27310-dc6e87.env
# output-file ~/.opam/log/ocsigenserver-27310-dc6e87.out
### output ###
# Usage: ocamlfind query        [-help | other options] <package_name> ...
# [...]
# Select toolchain with:
#   ocamlfind -toolchain <t> <command>
# Abbreviations:
#   e.g. ocamlfind opt instead of ocamlfind ocamlopt
# make[3]: *** [Makefile:44: ocsipersist.cmi] Error 2
# make[3]: Leaving directory '/home/anciety/.opam/default/.opam-switch/build/ocsigenserver.2.16.0/src/extensions/ocsipersist-pgsql'
# make[2]: *** [Makefile:53: byte] Error 2
# make[2]: Leaving directory '/home/anciety/.opam/default/.opam-switch/build/ocsigenserver.2.16.0/src/extensions'
# make[1]: *** [Makefile:7: all] Error 2
# make[1]: Leaving directory '/home/anciety/.opam/default/.opam-switch/build/ocsigenserver.2.16.0/src'
# make: *** [Makefile:8: all] Error 2
```

**Comment by Escapingbug** [comment]
There seems to be something wrong with ocsipersistent-pgsql, so I'll close the issue here.

**Comment by Escapingbug** [comment]
I did some research, it seems there's something wrong with `src/extensions/ocsipersistent-pgsql/Makefile`.

At line 7, `ocamlc` is directly concatenated with `${BYTEDBG}` which makes the command `ocamlc-g` instead of `ocamlc -g`, but the source code in the current master tree seems to be fine.

**Comment by Escapingbug** [comment]
Ok I found that patch. But opam version is not yet changed.

**Comment by jasonperry** [comment]
Since this is fixed in master, this could be closed. 
Someone could submit a pull request to [opam-repository](https://github.com/ocaml/opam-repository) to include the patch, or release a minor version of this package and wait for it to be updated on opam.

Until then, it can be installed with `opam --dev-repo`.

**Comment by martindemello** [comment]
to save someone else the trouble of reading the docs, the command is
```
opam pin --dev-repo ocsigenserver
```

(i had assumed it was a flag to `opam install` at first)

**Comment by jrochel** [comment]
Thanks! Here's the PR to the opam repository: https://github.com/ocaml/opam-repository/pull/17403
