### ISSUE TITLE
No more debug mode in 3.0.0

### ISSUE THREAD

**Issue by glondu** [ocsigen/ocsigenserver#200]
Since version 3.0.0, ocsigenserver does no longer accept `--debug`. I did not find an equivalent option, it seems impossible to get all logs.

**Comment by Zzull** [comment]
4.0.0? I'll try to restore it

**Comment by Zzull** [comment]
The option should be restored on the master branch

**Comment by glondu** [comment]
The latest version of ocsigenserver in opam is 3.0.0, which is very recent (June 30th). What version are downstream users supposed to use? Note that I use ocsigenserver via eliom, I am writing with my [Belenios](https://github.com/glondu/belenios) hat on.

**Comment by Zzull** [comment]
The latest one available from Opam (3.0.0) until we release the 4.0.0 (in the coming days)
