### ISSUE TITLE
ocsidbm error with ocsigenserver-4.0.1

### ISSUE THREAD

**Issue by ChrisVine** [ocsigen/ocsigenserver#205]
I have recently upgraded eliom to version 8.6.0 and ocsigenserver to version 4.0.1 via `opam upgrade`.  Following the upgrade there is a problem with persistent storage using the dbm backend.  This can be best reproduced by making a trivial helloworld project with `eliom-distillery -name helloworld -target-directory helloworld -template basic.ppx`.  With the default Makefile.option, building helloworld with `make opt` succeeds, but starting the server with `make test.opt` fails with:

```
ocsigenserver.opt: ocsigen:ocsipersist:dbm: Launching a new Ocsidbm process: /home/chris/.opam/eliom/lib/ocsigenserver/extensions/ocsidbm.exe on directory local/var/data/helloworld/ocsipersist
ocsigenserver.opt: ocsigen:ocsipersist:dbm: Cannot connect to Ocsidbm. Will continue without persistent session support. Error message is: No such file or directory in connect() .Have a look at the logs to see if there is an error message from the Ocsidbm process.
ocsigenserver.opt: main: Fatal - While loading /home/chris/.opam/eliom/lib/ocsigenserver/ext/ocsipersist-dbm/ocsipersistdbm.cmxs: execution of module initializers in the shared library failed: Unix.Unix_error(Unix.ENOENT, "connect", "")
make: *** [Makefile:60: test.opt] Error 52
```
The failure is not surprising because the $HOME/.opam/eliom/lib/ocsigenserver/extensions/ocsidbm.exe binary does not exist (in fact, the $HOME/.opam/eliom/lib/ocsigenserver/extensions directory does not exist).  There seem to be ocsigen components missing.

I have also recently upgraded to opam-2.1.0.  Possibly that has something to do with it.  The base compiler is ocaml-base-compiler.4.12.0.

**Comment by ChrisVine** [comment]
It seems to be a problem with ocsigenserver's installation target.  If I build ocsigenserver-4.0.1 by hand and then manually install the missing ocsidbm.exe and ocsidbm.bc files in opam's relevant ocsigenserver directory, then the helloworld example starts correctly.

You might also like to know that the manual build instructions in README.md are wrong.  You don't as stated «run "make" to compile».  You run «make ; dune build --profile {release,dev}» to compile.

**Comment by ChrisVine** [comment]
Applying this patch to src/extensions/ocsipersist-dbm/dune, adding an install stanza, works for me:

```
--- ocsigenserver-4.0.1/src/extensions/ocsipersist-dbm/dune.orig        2021-07-12 11:00:50.000000000 +0100
+++ ocsigenserver-4.0.1/src/extensions/ocsipersist-dbm/dune     2021-08-08 18:45:48.787044269 +0100
@@ -18,3 +18,9 @@
   (libraries lwt lwt.unix dbm ocsidbmtypes)
   (modes byte exe)
   (optional))
+
+(install
+  (files (ocsidbm.bc as extensions/ocsidbm.bc)
+         (ocsidbm.exe as extensions/ocsidbm.exe))
+  (section libexec)
+  (package ocsigenserver))
```

**Comment by Zzull** [comment]
Hello again. Sorry for the delay. We'll be taking another route actually because the current compilation scheme is unsatisfactory (as you might know…). Ocsipersist will become its own package for the good reason that ocsigenserver can work just fine without it. This should simplify the Makefiles and the Dune files and make your issue go away.

**Comment by Zzull** [comment]
Did the issue go away?

**Comment by ChrisVine** [comment]
I don't get this problem with ocsigenserver-5.0.0 (although you have to rebuild your configuration files).

**Comment by Zzull** [comment]
You're right. You need to adapt your configuration file to take into account the new name for Ocsipersist.

Closing
