### ISSUE TITLE
The documentation for creating links to services seems to be out of date

### ISSUE THREAD

**Issue by shonfeder** [ocsigen/ocsigenserver#247]
On https://ocsigen.org/eliom/dev/manual/server-links I find an example of how to create links like this:

```ocaml
open Eliom_content

 let links = Eliom_registration.Html.create
   ~path:(Eliom_service.Path ["rep";"links"])
   ~meth:(Eliom_service.Get Eliom_parameter.unit)
 (fun () () ->
   Lwt.return
    Html.D.(
      html
       (head (title (txt "Links")) [])
       (body
         [p
          [a theservice [txt "coucou"] (); br ();
           a hello [txt "hello"] (); br ();
           a default
             [txt "default page of the dir"] (); br ();
```

However, `D.a` seems to require services be supplied with the `~service` label. I gave a quick search on the `ocsigen` org to see where I would update this document, but didn't find an obvious file. If this needs updating, I can do it for this example if I get a pointer to the relevant file.

**Comment by balat** [comment]
Thank you! I will update it.
The documentation is in branch wikidoc https://github.com/ocsigen/eliom/tree/wikidoc/doc
(We should consider putting it back in main branch to make it more accessible).

**Comment by balat** [comment]
Done. It should update automatically the web site in a few minutes.

**Comment by shonfeder** [comment]
Thanks!
