### ISSUE TITLE
OPAM Upgrade Fails

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/ocsigenserver#82]
The OPAM configuration relies on ocamlfind to perform the uninstallation:

`remove: ["ocamlfind" "remove" "ocsigenserver"]`

ocamlfind does not remove subdirectories, as stated in its man page:

> Note  that package directories should be flat (no subdirectories); this
> subcommand cannot remove deep package directories.

Due to the files left behind, subsequent installation attempts fail, thus causing trouble with upgrades.

**Comment by Drup** [comment]
In the opam repo, the remove command is:
```
remove: ["rm" "-rf" "%{lib}%/ocsigenserver"]
```

Not sure why it was changed.

**Comment by vasilisp** [comment]
@drup, the change is yours :). Should we go back to the old behavior before the release?

**Comment by Drup** [comment]
I remember changing it because something else was broken, but I don't remember what.

**Comment by vbmithr** [comment]
Fixed by 43e236f92a795a0dcc5d1b32f954e61b0939b27c
