### ISSUE TITLE
Simple example for handler? 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/ocsigenserver#83]
I'm looking for a simple, self contained code sample that shows how to use ocsigenserver to handle requests. I don't see anything really relevant in the Ocsigen_* modules. Would greatly appreciate it, thanks.

**Comment by vasilisp** [comment]
Hi @fxfactorial,

I am assuming that your question is about Ocsigen as a whole, not just about ocsigenserver (which is a web server in the strict sense). Right?

I think that the [tutorial page](https://ocsigen.org/tuto/manual/) is a good starting point. You can find a range of self-contained "mini-tutorials", including one describing how to [define a simple service](https://ocsigen.org/tuto/4.2/manual/basicwebsite). The tutorials use Eliom, which is the Ocsigen language/framework for developing web applications. Does that help?

**Comment by fxfactorial** [comment]
I didn't mean Ocsigen as a whole, I meant specifically ocsigenserver. I wanted to use only ocsigenserver to handle a request.

**Comment by fxfactorial** [comment]
Okay, I guess this is not possible/feasible. I have instead gone with Cohttp then.
