### ISSUE TITLE
Regression in Ocsigenserver 2.7: some sites do not render correctly

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/ocsigenserver#97]
I've come across a really weird problem after the Ocsigenserver 2.7 update: the DOM tree parsed by the browser was not the same as the one generated by Eliom!  Looking at the HTML generated with 2.6 and 2.7, the only difference I can find is that in 2.7 the random string used (for example) by Eliom's non-attached co-services contains sometimes an actual forward slash `/` character.  I reckon this may be tripping the browser's parser... (I tested with Firefox and Chrome under Linux)

Were there changes in the Base64 encoder between 2.6 and 2.7?

**Comment by vasilisp** [comment]
> Were there changes in the Base64 encoder between 2.6 and 2.7?

Not on purpose, as far as I can tell. The [changelog](https://github.com/ocsigen/ocsigenserver/compare/764c39772efbdb5b390e9edd10a97f884946f841...2.7) is quite small, and the only change that looks suspicious to me is 284310fe8c48c139d8f1c968b873e8ed2bee5dfb (switch to `Lwt_io`, with some mismatch between writing strings/bytes). But this is a wild guess...

**Comment by darioteixeira** [comment]
I've taken a closer look, and it seems that the forward slash character also shows up sometimes with 2.6, and therefore the culprit is probably **not** the Base64 encoder (due to some random fluke, the slash character had not shown up in any of my initial tests with 2.6).

The only other difference I can find between 2.6 and 2.7 pertains to the content-type header: it was `application/xhtml+xml; charset=utf-8` in 2.6, and is `text/html; charset=utf-8` in 2.7.  Browsers have been known to use slightly different parsers for strict/loose content-types, which may be the culprit...

**Comment by vasilisp** [comment]
@darioteixeira, I can't say anything insightful at this time. You have way more experience with this combination than me, and I haven't reproduced the issue.

We would highly appreciate a failing example :). This will help us track down the incompatibility and (more importantly) fix the development versions if needed.

**Comment by vasilisp** [comment]
The above comment was meant for the OPAM issue, but no big difference :).

**Comment by darioteixeira** [comment]
I'm also having trouble reliably replicating the issue outside the main (large) application.  What I do know is the following:

  * after an `opam pin add ocsigenserver 2.6` and a recompilation, the app works fine.
  * after an `opam pin add ocsigenserver 2.7` and a recompilation, the app shows up garbled.

Looking at the generated HTML, it's clear why it is garbled with 2.7: the HTML is not even valid.  Here's the first few lines: (pretty-printed and with comments removed)

````html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Mixer1</title>
    <meta charset="utf-8">
    <link title="Default" media="all" type="text/css" href="Mixer1_files/default.css" rel="stylesheet">
    <script defer="defer" src="Mixer1_files/ceemi.js" type="text/javascript"></script>
</head>
````
Whereas the output with 2.6 is fine:

````html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>Mixer1</title>
    <meta charset="utf-8" />
    <link title="Default" media="all" type="text/css" href="Mixer2_files/default.css" rel="stylesheet" />
    <script defer="defer" src="Mixer2_files/ceemi.js" type="text/javascript"></script>
</head>
</html>
````
I've been playing with smaller examples, but with those the only difference I can find between 2.6 and 2.7 is the change in `content-type` on the HTTP headers...

Now, I really can't explain why invalid HTML is being generated by this app but only with Ocsigenserver 2.7.  (I'm only using safe Eliom/Tyxml, with no injection of unsafe raw HTML.)

**Comment by darioteixeira** [comment]
I've edited the title of this ticket, as the culprit may not be the forward slash character.

Anyway, I've done some further experiments: using `wget`, the retrieved HTML is the same using Ocsigenserver 2.6 and 2.7.  However, using Firefox or Chrome on Linux, the page does not render correctly with Ocsigenserver 2.7 (and using the Developer Tools I can verify that the HTML tree is not being parsed correctly).  I also got reports from a third party that the application has the same rendering issues with Safari on iOS, but only with Ocsigenserver 2.7.

Anyway, so far the only difference I can find is the change in content-type.  Any ideas on what else I should try to get to the bottom of this?

**Comment by vouillon** [comment]
Hi Dario!

The `content-type` has been changed as the previous content type triggered a bug in Chrome : a single long running XHR request would block all other requests to the same site.

In HTML, the closing tag can be omitted, so your sample output looks fine to me.

In what way is the HTML document misparsed?

**Comment by darioteixeira** [comment]
Hi Jérôme,

After some head-scratching, I have another hypothesis as to why there's a mismatch: the page has a form inside a form (the inner form contains just a button to a non-attached co-service).  For some reason, browsers accepted this nesting of forms with the old content-type, but not with the newer one.

I'm attaching three files:

  * `wget.html` contains the contents of the page as retrieved via wget.  Its contents are the same using either Ocsigenserver 2.6 or 2.7.
  * `firefox26.xhtml` is the result of doing **Save As** under Firefox when the server is running Ocsigenserver 2.6.  Note the Firefox adds the `xhtml` extension.
  * `firefox27.html` is the result of doing **Save As** under Firefox when the server is running Ocsigenserver 2.7.  Note that the extension added by Firefox is now `html`.

Note that the trees expressed by `firefox26.xhtml` and `firefox27.html` differ ever so slightly, and the culprit is most likely the inner form.

Anyway, I reckon that forms inside forms may not even be legal Html, in which case the fault lies on my part.  Though in that case Tyxml may also be a bit too lenient...

(Note: to please Github I've added the extension `.txt` to all files)

[wget.html.txt](https://github.com/ocsigen/ocsigenserver/files/245143/wget.html.txt)
[firefox26.xhtml.txt](https://github.com/ocsigen/ocsigenserver/files/245144/firefox26.xhtml.txt)
[firefox27.html.txt](https://github.com/ocsigen/ocsigenserver/files/245145/firefox27.html.txt)
