### ISSUE TITLE
SSLv3 build error

### ISSUE THREAD

**Issue by nicolaction** [ocsigen/ocsigenserver#98]
While doing my periodical upgrade, I came across a problem when building ocsigenserver 2.7.

`# File "_none_", line 1:`
`# Error: Error on dynamically loaded library: /home/nicolas/.opam/4.02.3/lib/stublibs/dllssl_threads_stubs.so: /home/nicolas/.opam/4.02.3/lib/stublibs/dllssl_threads_stubs.so: undefined symbol: SSLv3_client_method`
`# make[2]: *** [ocsigenserver] Erreur 2`
`# make[1]: *** [all] Erreur 2`
`# make: *** [all] Erreur 2`

I looked it up a bit, and it seems related to the fact that recent builds of openssl in Arch Linux have ditched SSLv3 altogether for security reasons.

Is there a way to build ocsigenserver nevertheless?
And as a follow-up, is it possible not to depend on SSLv3?

Thank you in advance for your help.

**Comment by vasilisp** [comment]
Could you recompile the `ssl` package (`opam reinstall ssl`), to which `dllssl_threads_stubs.so` belongs? If `ssl` is really broken, that must be affecting numerous other OPAM packages.

**Comment by nicolaction** [comment]
Indeed, recompiling ssl did the trick.
False alarm.
Thank you for your help!
